### ISSUE TITLE
Blog title preview is cut off and doesn't wrap

### ISSUE THREAD

**Issue by ckipp01** [lunatech-labs/lunatech-com-website-2020#2]
<img width="559" alt="Screenshot 2020-06-28 at 18 53 44" src="https://user-images.githubusercontent.com/13974112/85953467-cb822080-b970-11ea-99de-d69e4cc7e24f.png">

I'd be nice if the entire title would just wrap so it's visible for the user. The way it is now cuts off both the blog title and the date.

This looks to be happening on both Firefox and Chrome.

**Comment by pepite** [comment]
Thanks, could you please use [Jira](https://lunatech.atlassian.net/jira/software/projects/LGW/boards/10) for any further discovery?

**Comment by pepite** [comment]
Should be fixed now.

**Comment by ckipp01** [comment]
> Thank, could you use [Jira](https://lunatech.atlassian.net/jira/software/projects/LGW/boards/10) for any further discovery?

Ah, yup, will do 👍
